task: hellaswag_bg
tag:
  - hellaswag_bulgarian
output_type: multiple_choice
dataset_path: petkopetkov/hellaswag-bg
training_split: null
validation_split: validation
test_split: null
process_docs: !function utils.process_docs
doc_to_text: "query"
doc_to_target: "{{label.lstrip()}}"
doc_to_choice: "choices"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0