task: mathqa_bg
tag:
  - mathqa_bulgarian
dataset_path: petkopetkov/math_qa-bg
output_type: multiple_choice
training_split: train
validation_split: validation
test_split: test
doc_to_text: "Задача: {{Problem}}\nОтговори:"
doc_to_target: "{{['a', 'b', 'c', 'd', 'e'].index(correct)}}"
doc_to_choice: !function utils.doc_to_choice
should_decontaminate: true
doc_to_decontamination_query: "Задача: {{Problem}}\nОтговори:"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
