task: arc_challenge_bg
tag:
  - arc_challenge_bulgarian
dataset_path: petkopetkov/arc-challenge-bg
output_type: multiple_choice
training_split: train
validation_split: validation
test_split: test
doc_to_text: "Въпрос: {{question}}\nОтговор:"
doc_to_target: "{{choices.label.index(answerKey)}}"
doc_to_choice: "{{choices.text}}"
should_decontaminate: true
doc_to_decontamination_query: "Въпрос: {{question}}\nОтговор:"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
